name: drun
version: 0.0.0-semantically-released
homepage: https://github.com/brad-jones/drun
description: A dartlang task runner, write functions and call them in your terminal.

environment:
  sdk: ">=2.7.0 <3.0.0"

executables:
  drun:

dependencies:
  args: ^1.5.3
  console: ^3.1.0
  dexeca: ^1.0.1
  dexecve: ^1.1.0
  io: ^0.3.3
  recase: ^3.0.0

dev_dependencies:
  archive: ^2.0.13
  crypto: ^2.1.4
  path: ^1.6.4
  pedantic: ^1.8.0
  pretty_json: ^1.0.8
  test: ^1.14.1
